services:
    _defaults:
        public: true

    hello.command:
        class: 'AdielSeffrinBot\Commands\HelloCommand'
        arguments: ['@AdielSeffrinBot\Services\HelloService']
        calls:
            - ['execute']
