parameters:
    pdo.class: PDO
    pdo.attr_errmode: 3
    pdo.erromode_exception: 2
    #database config
    database.driver: '%env(DATABASE_DRIVER)%'
    database.host: '%env(DATABASE_HOST)%'
    database.name: '%env(DATABASE_NAME)%'
    database.password: '%env(DATABASE_PASSWORD)%'
    database.port: '%env(DATABASE_PORT)%'
    database.user: '%env(DATABASE_USER)%'
    database.dsn: '%database.driver%:host=%database.host%;port=%database.port%;dbname=%database.name%'

services:
    _defaults:
        autoconfigure: true
        public: true
    
    database:
        class: '%pdo.class%'
        arguments:
        - '%database.dsn%'
        - '%database.user%'
        - '%database.password%'
        - 'option': ['%pdo.attr_errmode%', '%pdo.erromode_exception%']

    hungry.repository:
        class: 'AdielSeffrinBot\Repositories\HungryRepository'
        arguments: ['@database']
    
    user.repository:
        class: 'AdielSeffrinBot\Repositories\UserRepository'
        arguments: ['@database']
