parameters:
    pdo.class: PDO
    pdo.attr_errmode: 3
    pdo.erromode_exception: 2
    #database config
    database.driver: '%env(DATABASE_DRIVER)%'
    database.host: '%env(DATABASE_HOST)%'
    database.name: '%env(DATABASE_NAME)%'
    database.password: '%env(DATABASE_PASSWORD)%'
    database.port: '%env(DATABASE_PORT)%'
    database.user: '%env(DATABASE_USER)%'
    database.dsn: '%database.driver%:host=%database.host%;port=%database.port%;dbname=%database.name%'
    
    #twitch config
    twitch.channel: '%env(TWITCH_CHANNEL)%'
    twitch.host: '%env(TWITCH_HOST)%'
    twitch.port: '%env(TWITCH_PORT)%'
    twitch.password: '%env(TWITCH_PASSWORD)%'
    twitch.nickname: '%env(TWITCH_NICKNAME)%'

    #twitter config
    twitter.api_key: '%env(TWITTER_API_KEY)%'
    twitter.secret_key: '%env(TWITTER_SECRET_KEY)%'
    twitter.access_token: '%env(TWITTER_ACCESS_TOKEN)%'
    twitter.secret_token: '%env(TWITTER_SECRET_TOKEN)%'
    twitter.bearer_token: '%env(TWITTER_BEARER_TOKEN)%'
    
services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true

    AdielSeffrinBot\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Models}'
    
    database:
        class: '%pdo.class%'
        arguments:
        - '%database.dsn%'
        - '%database.user%'
        - '%database.password%'
        - 'option': ['%pdo.attr_errmode%', '%pdo.erromode_exception%']
    
    
    bot.connection:
        class: '\Phergie\Irc\Connection'
        arguments:
            - { serverHostname: '%twitch.host%', 
                serverPort: '%twitch.port%',
                password: '%twitch.password%',
                nickname: '%twitch.nickname%',
                username: '%twitch.nickname%'
            }

    bot.client:
        class: '\Phergie\Irc\Client\React\Client'

    AdielSeffrinBot\Services\TwitterService:
        arguments: 
            - '%twitter.api_key%'
            - '%twitter.secret_key%'
            - '%twitter.access_token%'
            - '%twitter.secret_token%'
            - '%twitter.bearer_token%'
    
    AdielSeffrinBot\Repositories\HungryRepository:
        arguments: ['@database']
    
    AdielSeffrinBot\Repositories\UserRepository:
        arguments: ['@database']
    
    AdielSeffrinBot\Services\HungryService:
        arguments: ['@AdielSeffrinBot\Repositories\HungryRepository']

    AdielSeffrinBot\Services\UserService:
        arguments: ['@AdielSeffrinBot\Repositories\UserRepository']

    AdielSeffrinBot\Adapters\PhergieClientAdapter:
        arguments:
            - '@bot.client'
            - '@bot.connection'
            - '@service_container'
        calls:
            - ['connect']