imports:
    - { resource: 'commands.yml'}
    - { resource: 'repositories.yml'}

parameters:
   
    #twitch config
    twitch.channel: '%env(TWITCH_CHANNEL)%'
    twitch.host: '%env(TWITCH_HOST)%'
    twitch.port: '%env(TWITCH_PORT)%'
    twitch.password: '%env(TWITCH_PASSWORD)%'
    twitch.nickname: '%env(TWITCH_NICKNAME)%'

    #twitter config
    twitter.api_key: '%env(TWITTER_API_KEY)%'
    twitter.secret_key: '%env(TWITTER_SECRET_KEY)%'
    twitter.access_token: '%env(TWITTER_ACCESS_TOKEN)%'
    twitter.secret_token: '%env(TWITTER_SECRET_TOKEN)%'
    twitter.bearer_token: '%env(TWITTER_BEARER_TOKEN)%'
    
services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true

    AdielSeffrinBot\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Models}'
    
    bot.connection:
        class: '\Phergie\Irc\Connection'
        arguments:
            - { serverHostname: '%twitch.host%', 
                serverPort: '%twitch.port%',
                password: '%twitch.password%',
                nickname: '%twitch.nickname%',
                username: '%twitch.nickname%'
            }

    bot.client:
        class: '\Phergie\Irc\Client\React\Client'

    AdielSeffrinBot\Services\TwitterService:
        arguments: 
            - '%twitter.api_key%'
            - '%twitter.secret_key%'
            - '%twitter.access_token%'
            - '%twitter.secret_token%'
            - '%twitter.bearer_token%'
    
    AdielSeffrinBot\Services\HungryService:
        arguments: ['@hungry.repository']

    AdielSeffrinBot\Services\UserService:
        arguments: ['@user.repository']

    AdielSeffrinBot\Adapters\PhergieClientAdapter:
        arguments:
            - '@bot.client'
            - '@bot.connection'
            - '@service_container'
        calls:
            - ['connect']
